# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-21 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('address', models.EmailField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('annotation', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': '邮箱',
                'verbose_name_plural': '邮箱',
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词',
                'ordering': ['keyword'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['time'], 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AddField(
            model_name='project',
            name='sourceId',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(),
        ),
    ]
