# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-17 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['time'], 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
    ]
