# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-21 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190621_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('sourceId', models.IntegerField(default=-1)),
            ],
            options={
                'verbose_name': '最新项目',
                'verbose_name_plural': '最新项目',
                'ordering': ['sourceId'],
            },
        ),
    ]
