# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-20 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190620_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(),
        ),
    ]
