# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-17 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190617_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
