# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-21 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_lastproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastproject',
            name='sourceId',
            field=models.IntegerField(unique=True),
        ),
    ]
