# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-17 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailAddress', models.EmailField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': '邮箱',
                'verbose_name_plural': '邮箱',
            },
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['keyword'], 'verbose_name': '关键词', 'verbose_name_plural': '关键词'},
        ),
    ]
