# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-19 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190617_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='emailAddress',
            new_name='address',
        ),
        migrations.AddField(
            model_name='email',
            name='annotation',
            field=models.CharField(default=1, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
