# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-19 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20190620_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='id',
        ),
        migrations.AlterField(
            model_name='email',
            name='address',
            field=models.EmailField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
